CREATE DATABASE IF NOT EXISTS hospital_db;
USE hospital_db;

CREATE TABLE PATIENT (
    PATIENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DOB DATE,
    GENDER VARCHAR(255),
    CONTACT_NUMBER VARCHAR(255)
);

INSERT INTO PATIENT (PATIENT_ID, FIRST_NAME, LAST_NAME, DOB, GENDER, CONTACT_NUMBER)
VALUES
(1, 'Alice', 'Johnson', '1990-05-15', 'F', '123-456-7890'),
(2, 'Bob', 'Smith', '1985-07-20', 'M', '234-567-8901'),
(3, 'Carol', 'Brown', '2000-09-10', 'F', '345-678-9012'),
(4, 'David', 'White', '1995-02-12', 'M', '456-789-0123');


CREATE TABLE MEDICAL_RECORD (
    RECORD_ID INT PRIMARY KEY,
    PATIENT_ID INT,
    DIAGNOSIS VARCHAR(255),
    TREATMENT VARCHAR(255),
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
    );
    
INSERT INTO MEDICAL_RECORD (RECORD_ID, PATIENT_ID, DIAGNOSIS, TREATMENT, ADMISSION_DATE, DISCHARGE_DATE)
VALUES
(1, 1, 'Flu', 'Rest and Medication', '2024-01-15', '2024-01-18'),
(2, 2, 'Broken Arm', 'Cast and Pain Relief', '2024-02-10', '2024-02-20'),
(3, 3, 'Asthma', 'Inhalers and Monitoring', '2024-03-05', '2024-03-15'),
(4, 4, 'High Fever', 'Antibiotics', '2024-03-01', '2024-03-25');

SELECT COUNT(*) AS TotalPatients FROM PATIENT;

SELECT COUNT(*) AS TotalDiagnoses FROM MEDICAL_RECORD;

SELECT * FROM PATIENT p
JOIN MEDICAL_RECORD mr ON p.PATIENT_ID = mr.PATIENT_ID
WHERE mr.ADMISSION_DATE > '2024-01-01';

SELECT * FROM PATIENT WHERE CONTACT_NUMBER LIKE '234%';

SELECT * FROM PATIENT p
JOIN MEDICAL_RECORD mr ON p.PATIENT_ID = mr.PATIENT_ID
WHERE mr.DISCHARGE_DATE < '2024-03-01';

SELECT * FROM PATIENT p
INNER JOIN MEDICAL_RECORD mr ON p.PATIENT_ID = mr.PATIENT_ID;

SELECT * FROM PATIENT p
LEFT JOIN MEDICAL_RECORD mr ON p.PATIENT_ID = mr.PATIENT_ID;

SELECT * FROM MEDICAL_RECORD mr
RIGHT JOIN PATIENT p ON mr.PATIENT_ID = p.PATIENT_ID;

SELECT DISTINCT TREATMENT FROM MEDICAL_RECORD;

SELECT * FROM PATIENT WHERE GENDER = 'F' AND DOB > '1990-01-01';

SELECT * FROM MEDICAL_RECORD WHERE TREATMENT NOT LIKE '%Pain Relief%';

SELECT * FROM PATIENT WHERE FIRST_NAME LIKE 'A%';

SELECT * FROM MEDICAL_RECORD 
WHERE ADMISSION_DATE BETWEEN '2024-01-01' AND '2024-03-31';

SELECT * FROM MEDICAL_RECORD 
WHERE TREATMENT LIKE '%Inhaler%' OR DIAGNOSIS LIKE 'High%';
